
spring:
   cloud:
      config:
         server:
            git:
               uri: https://github.com/manhbui98/configQlsc
               username: manhbui98@gmail.com
               password: buimanh98
server:
   port: 8761
eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
management:
   endpoints:
      web:
         exposure:
            include: "*"
